settings:
  auto-update: true
  debug: false

# If enabled, events will start automatically
scheduler:
  enabled: true
  # For the frequency, use the quartz cron syntax
  # frequency: "0 0 * * *" Every day at midnight
  events:
    1:
      name: craft-event
      frequency: "0 50 22 * * ?" # Every day at 22:50